"""Scaffold a publishable x402-paid service wrapper (Cloudflare Monetization Gateway parity).

Generates output/<name>/start.py that supervises [your upstream] + [x402 gateway].
Then the agent runs:  preview(serve, dir=output/<name>, command='python3 start.py',
port=<gateway_port>)  ->  community-publish.publish_preview(...)  -> public paid URL.

Usage:
  python3 skills/x402/scripts/make_public.py --name my-paid-api \
      --upstream-port 5173 --mode payperuse --route 'GET /api/*=$0.01' \
      --pay-to 0xYourWallet [--gateway-port 8420] [--pass-days 30 --pass-price 4.99] \
      [--price-per-credit 0.01 --min-credits 100] [--networks all]

Networks (plans-280-04 §5.6.4):
  --networks all            follow the platform mainnet full set (default)
  --networks eip155:8453    custom lock to a comma-separated CAIP-2 list
"""
import argparse, json, os, sys

WS = "/data/workspace"
# Default: platform facilitator (starchild-x402-facilitator.fly.dev) —
# settler maintained by the platform, no local gas needed. Override via
# --facilitator / X402_FACILITATOR_URL for a custom facilitator.
FACILITATOR = os.environ.get("X402_FACILITATOR_URL", "https://starchild-x402-facilitator.fly.dev")

ap = argparse.ArgumentParser()
ap.add_argument("--name", required=True)
ap.add_argument("--upstream-port", type=int, required=True)
ap.add_argument("--mode", choices=["payperuse", "subscription", "metered", "timepass"], default="payperuse")
ap.add_argument("--route", action="append", default=[], help="'METHOD /path=$price' (payperuse) or 'METHOD /path=units' (metered)")
ap.add_argument("--pay-to", required=True)
ap.add_argument("--gateway-port", type=int, default=8420)
ap.add_argument("--networks", default="all",
                help="'all' (default) = platform mainnet full set; or comma-separated CAIP-2 list")
ap.add_argument("--network", default="",
                help="DEPRECATED: use --networks. Single-chain custom lock if set.")
ap.add_argument("--facilitator", default=FACILITATOR)
ap.add_argument("--facilitator-token", default=os.environ.get("X402_FACILITATOR_TOKEN", ""),
                help="bearer token if the facilitator enforces caller auth")
ap.add_argument("--price-per-credit", type=float, default=0.01)
ap.add_argument("--min-credits", type=int, default=100)
ap.add_argument("--pass-days", type=float, default=30)
ap.add_argument("--pass-price", default="4.99")
args = ap.parse_args()

# Networks resolution (plans-280-04 §5.6.4) — align with monetize.py default "all"
if args.network:
    networks_list = [n.strip() for n in args.network.split(",") if n.strip()]
    networks_mode = "custom"
elif args.networks.strip().lower() == "all":
    networks_list = []
    networks_mode = "all"
else:
    networks_list = [n.strip() for n in args.networks.split(",") if n.strip()]
    networks_mode = "custom" if networks_list else "all"

routes = {}
for r in args.route or ["GET /api/*=$0.01"]:
    spec, _, val = r.rpartition("=")
    if args.mode == "payperuse":
        routes[spec] = {"price": val if val.startswith("$") else f"${val}"}
    else:
        routes[spec] = {"units": int(val) if val.isdigit() else 1}

# NOTE: make_public scaffolds LEGACY modes only (payperuse/subscription/
# metered/timepass). Those paths advertise a single network (NETWORKS[0])
# even when networks_mode=all. For marketplace multi-accepts (Base+Monad+Robinhood+X Layer+Solana),
# use monetize.py --mode pay_per_use (platform mode) instead.
cfg = {"mode": args.mode, "port": args.gateway_port,
       "upstream": f"http://127.0.0.1:{args.upstream_port}",
       "pay_to": args.pay_to,
       "networks_mode": networks_mode,
       **({"networks": networks_list} if networks_mode == "custom" and networks_list else {}),
       "facilitator": args.facilitator,
       **({"facilitator_token": args.facilitator_token} if args.facilitator_token else {}),
       "state_dir": os.path.join(WS, ".x402", args.name, "state"),
       "routes": routes}
if args.mode in ("subscription", "metered"):
    cfg["topup"] = {"price_per_credit_usd": args.price_per_credit, "min_credits": args.min_credits}
elif args.mode == "timepass":
    cfg["topup"] = {"price_usd": str(args.pass_price), "pass_days": args.pass_days}

out = os.path.join(WS, "output", args.name)
os.makedirs(out, exist_ok=True)
d = os.path.join(WS, ".x402", args.name)
os.makedirs(d, exist_ok=True)
cfg_path = os.path.join(d, "x402.config.json")
json.dump(cfg, open(cfg_path, "w"), indent=1)

start = f'''"""auto-generated by make_public.py — supervises x402 gateway for {args.name}.
Assumes your upstream service on port {args.upstream_port} is started separately
(preview command can chain it: 'python3 my_service.py & python3 start.py')."""
import os, subprocess, sys, time
env = {{**os.environ, "X402_CONFIG": {cfg_path!r}}}
gw = subprocess.Popen([sys.executable, "/data/workspace/skills/x402/gateway/app.py"], env=env)
while True:
    time.sleep(5)
    if gw.poll() is not None:
        sys.exit(1)
'''
open(os.path.join(out, "start.py"), "w").write(start)
print(json.dumps({"ok": True, "dir": f"output/{args.name}", "config": cfg_path,
                  "gateway_port": args.gateway_port, "mode": args.mode,
                  "networks_mode": networks_mode,
                  "networks": (networks_list or "all (legacy modes still advertise NETWORKS[0] only)"),
                  "routes": routes,
                  "note": "Legacy modes only advertise one network in 402. "
                          "For Base+Monad+Robinhood+X Layer+Solana multi-accepts use monetize.py "
                          "--mode pay_per_use (platform mode).",
                  "next": [
                      f"preview(serve, title='{args.name}', dir='output/{args.name}', command='python3 start.py', port={args.gateway_port})",
                      f"community-publish.publish_preview(preview_id, slug='{args.name}')",
                      "public discovery: <public-url>/.well-known/x402"]}, indent=1))
