#!/usr/bin/env bash
# connector_edge_cases_regenerate_log.sh — regenerate test-results/connector_edge_cases.log
#
# Per coding_agent_session_search-4z5uc. Runs the full connector test suite
# and captures stdout+stderr to test-results/connector_edge_cases.log with an
# embedded header (commit SHA, rustc version, date) so future audits can
# verify the log matches the tree at a known point.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RCH_TARGET_DIR="${RCH_TARGET_DIR:-/tmp/cass-4z5uc-target}"
LOG_DIR="$PROJECT_ROOT/test-results"
LOG_FILE="$LOG_DIR/connector_edge_cases.log"
mkdir -p "$LOG_DIR"

# Build header.
COMMIT="$(git -C "$PROJECT_ROOT" rev-parse HEAD)"
COMMIT_SHORT="$(git -C "$PROJECT_ROOT" rev-parse --short HEAD)"
BRANCH="$(git -C "$PROJECT_ROOT" rev-parse --abbrev-ref HEAD)"
RUSTC_VER="$(rustc --version 2>/dev/null || echo 'rustc-unknown')"
DATE_UTC="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
HOST="$(uname -a)"

cat > "$LOG_FILE" <<EOF
# connector_edge_cases.log
# Generated by scripts/tests/connector_edge_cases_regenerate_log.sh
# (per coding_agent_session_search-4z5uc)
#
# commit:        $COMMIT
# commit_short:  $COMMIT_SHORT
# branch:        $BRANCH
# rustc:         $RUSTC_VER
# date_utc:      $DATE_UTC
# host:          $HOST
#
# Re-generate via: bash scripts/tests/connector_edge_cases_regenerate_log.sh
# ===============================================================================
EOF

START_TS="$(date +%s)"
RC=0
echo "[regenerate] Running cargo test --lib connectors..." | tee -a "$LOG_FILE"
if rch exec -- env CARGO_TARGET_DIR="$RCH_TARGET_DIR" \
    cargo test --lib connectors -- --nocapture --test-threads=1 \
    >> "$LOG_FILE" 2>&1; then
    echo "[regenerate] cargo test --lib connectors PASSED" | tee -a "$LOG_FILE"
else
    RC=$?
    echo "[regenerate] cargo test --lib connectors FAILED with exit $RC" | tee -a "$LOG_FILE"
fi

# Also run the integration connector tests.
echo "[regenerate] Running integration connector tests..." | tee -a "$LOG_FILE"
for test_file in "$PROJECT_ROOT/tests/connector_"*.rs; do
    test_name="$(basename "$test_file" .rs)"
    echo "[regenerate]   integration: $test_name" | tee -a "$LOG_FILE"
    rch exec -- env CARGO_TARGET_DIR="$RCH_TARGET_DIR" \
        cargo test --test "$test_name" -- --nocapture \
        >> "$LOG_FILE" 2>&1 || RC=$?
done

ELAPSED_S=$(( $(date +%s) - START_TS ))

# Append summary footer.
TOTAL_TESTS="$(grep -E "^running [0-9]+ tests?" "$LOG_FILE" | awk '{s+=$2} END {print s}')"
PANIC_COUNT="$(grep -c "thread '.*' panicked" "$LOG_FILE" || true)"
TEST_OK_COUNT="$(grep -c "^test result: ok" "$LOG_FILE" || true)"
TEST_FAIL_COUNT="$(grep -c "^test result: FAILED" "$LOG_FILE" || true)"

cat >> "$LOG_FILE" <<EOF

# ===============================================================================
# SUMMARY (footer)
# elapsed_seconds: $ELAPSED_S
# total_tests:     ${TOTAL_TESTS:-0}
# panic_count:     ${PANIC_COUNT:-0}
# test_result_ok:  ${TEST_OK_COUNT:-0}
# test_result_fail: ${TEST_FAIL_COUNT:-0}
# overall_exit:    $RC
EOF

echo ""
echo "[regenerate] Log written to $LOG_FILE ($ELAPSED_S sec)"
echo "[regenerate] Embedded commit: $COMMIT"
echo "[regenerate] Tests: ${TOTAL_TESTS:-0} total, ${PANIC_COUNT:-0} panics, exit $RC"

# Return the underlying test exit code so CI can react.
exit "$RC"
