#!/usr/bin/env bash
# vz9t8_8_virtual_list_perf_e2e.sh — orchestrate virtual-list perf + correctness tests.
#
# Per coding_agent_session_search-vz9t8.8.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RCH_TARGET_DIR="${RCH_TARGET_DIR:-/tmp/cass-vz9t8-8-target}"
LOG="$RCH_TARGET_DIR/virtual-list-perf-e2e.log"
SUMMARY="$RCH_TARGET_DIR/virtual-list-summary.md"
mkdir -p "$RCH_TARGET_DIR"
exec > >(tee -a "$LOG") 2>&1

cleanup() {
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        echo ""
        echo "[vz9t8_8_e2e] FAILURE — last 50 log lines:" >&2
        tail -n 50 "$LOG" | sed 's/^/[vz9t8_8_e2e]   /' >&2
    fi
    exit "$rc"
}
trap cleanup EXIT

cd "$PROJECT_ROOT/tests"
TEST_OUT="$RCH_TARGET_DIR/playwright.out"
echo "[vz9t8_8_e2e] running playwright spec virtual-list-perf.spec.ts"
PASS=0
FAIL=0
if npx playwright test e2e/rendering/virtual-list-perf.spec.ts --reporter=list \
    > "$TEST_OUT" 2>&1; then
    if grep -qE "passed|test result.*ok" "$TEST_OUT"; then
        echo "[vz9t8_8_e2e] OK: playwright tests passed"
        PASS=$((PASS + 1))
    else
        echo "[vz9t8_8_e2e] FAIL: cargo exited 0 but no 'passed' marker"
        tail -50 "$TEST_OUT" | sed 's/^/[vz9t8_8_e2e]   /'
        FAIL=$((FAIL + 1))
    fi
else
    rc=$?
    echo "[vz9t8_8_e2e] FAIL: playwright exited $rc"
    tail -80 "$TEST_OUT" | sed 's/^/[vz9t8_8_e2e]   /'
    FAIL=$((FAIL + 1))
fi

# Build markdown summary from console.info events.
{
    echo "# Virtual List Perf Summary"
    echo ""
    echo "Generated by scripts/tests/vz9t8_8_virtual_list_perf_e2e.sh"
    echo ""
    echo "## Performance results"
    echo ""
    grep -E "perf_test_result|stress_100k_result|scroll_preserve" "$TEST_OUT" | sed 's/^/    /' || true
    echo ""
    echo "## Pass/Fail"
    echo "PASS=$PASS FAIL=$FAIL"
} > "$SUMMARY"

echo ""
echo "[vz9t8_8_e2e] SUMMARY: PASS=$PASS FAIL=$FAIL"
echo "[vz9t8_8_e2e] log: $LOG"
echo "[vz9t8_8_e2e] summary: $SUMMARY"
[ "$FAIL" -eq 0 ] && echo "[vz9t8_8_e2e] ALL PASS" || exit 1
