#!/usr/bin/env bash
# vz9t8_1_wcag_aa_e2e.sh — WCAG AA contrast sweep across all theme presets.
#
# Per coding_agent_session_search-vz9t8.1. Runs the unit-test suite that
# computes contrast ratios for every preset × token pair and emits a
# markdown summary report.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RCH_TARGET_DIR="${RCH_TARGET_DIR:-/tmp/cass-vz9t8-1-target}"
LOG="$RCH_TARGET_DIR/wcag-aa-e2e.log"
REPORT="$RCH_TARGET_DIR/wcag-report.md"
mkdir -p "$RCH_TARGET_DIR"
exec > >(tee -a "$LOG") 2>&1

cleanup() {
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        echo ""
        echo "[vz9t8_1_e2e] FAILURE — last 50 log lines:" >&2
        tail -n 50 "$LOG" | sed 's/^/[vz9t8_1_e2e]   /' >&2
    fi
    exit "$rc"
}
trap cleanup EXIT

PASS=0
FAIL=0

# Run the cargo test under RUST_LOG=info so the structured tracing rows are captured.
TEST_OUT="$RCH_TARGET_DIR/wcag-aa-test.out"
echo "[vz9t8_1_e2e] running cargo test ui_high_contrast_wcag_aa"
if rch exec -- env CARGO_TARGET_DIR="$RCH_TARGET_DIR" RUST_LOG=info \
    cargo test --test ui_high_contrast_wcag_aa -- --nocapture --test-threads=1 \
    > "$TEST_OUT" 2>&1; then
    if grep -q "test result: ok" "$TEST_OUT"; then
        echo "[vz9t8_1_e2e] OK: WCAG tests passed"
        PASS=$((PASS + 1))
    else
        echo "[vz9t8_1_e2e] FAIL: cargo exited 0 but no 'test result: ok' marker"
        FAIL=$((FAIL + 1))
    fi
else
    echo "[vz9t8_1_e2e] FAIL: cargo test failed — see $TEST_OUT"
    tail -50 "$TEST_OUT" | sed 's/^/[vz9t8_1_e2e]   /'
    FAIL=$((FAIL + 1))
fi

# Generate a markdown report from the captured tracing rows.
echo "[vz9t8_1_e2e] generating $REPORT"
{
    echo "# WCAG AA Contrast Report"
    echo ""
    echo "Generated by scripts/tests/vz9t8_1_wcag_aa_e2e.sh"
    echo ""
    echo "## Per-token measurements"
    echo ""
    echo "| Preset | Token | Ratio | AA Pass |"
    echo "|--------|-------|------:|---------|"
    grep -oE "preset=[^[:space:]]+ token=[^[:space:]]+ ratio=[^[:space:]]+ aa_pass=[^[:space:]]+" "$TEST_OUT" \
        | head -200 \
        | sed -E 's/preset=([^[:space:]]+) token=([^[:space:]]+) ratio=([^[:space:]]+) aa_pass=([^[:space:]]+)/| \1 | \2 | \3 | \4 |/' \
        || true
} > "$REPORT"

echo ""
echo "[vz9t8_1_e2e] SUMMARY: PASS=$PASS FAIL=$FAIL"
echo "[vz9t8_1_e2e] log: $LOG"
echo "[vz9t8_1_e2e] report: $REPORT"
[ "$FAIL" -eq 0 ] && echo "[vz9t8_1_e2e] ALL PASS" || exit 1
