#!/usr/bin/env bash
# vz9t8_7_integrity_tofu_e2e.sh — orchestrate the integrity-TOFU Playwright spec.
#
# Per coding_agent_session_search-vz9t8.7. Runs the browser-side TOFU tests
# and aggregates results into a markdown summary.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RCH_TARGET_DIR="${RCH_TARGET_DIR:-/tmp/cass-vz9t8-7-target}"
LOG="$RCH_TARGET_DIR/integrity-tofu-e2e.log"
SUMMARY="$RCH_TARGET_DIR/integrity-tofu-summary.md"
mkdir -p "$RCH_TARGET_DIR"
exec > >(tee -a "$LOG") 2>&1

cleanup() {
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        echo ""
        echo "[vz9t8_7_e2e] FAILURE — last 50 log lines:" >&2
        tail -n 50 "$LOG" | sed 's/^/[vz9t8_7_e2e]   /' >&2
    fi
    exit "$rc"
}
trap cleanup EXIT

PASS=0
FAIL=0

# Run the playwright spec. The project's playwright.config.ts handles all
# configuration; we just point at the spec.
echo "[vz9t8_7_e2e] running playwright spec integrity-tofu.spec.ts"
cd "$PROJECT_ROOT/tests"
TEST_OUT="$RCH_TARGET_DIR/playwright.out"
if npx playwright test e2e/encryption/integrity-tofu.spec.ts \
    --reporter=list \
    > "$TEST_OUT" 2>&1; then
    if grep -qE "passed|test result.*ok" "$TEST_OUT"; then
        passed_count=$(grep -oE "[0-9]+ passed" "$TEST_OUT" | head -1 | grep -oE "[0-9]+" || echo 0)
        echo "[vz9t8_7_e2e] OK: $passed_count playwright test(s) passed"
        PASS=$((PASS + 1))
    else
        echo "[vz9t8_7_e2e] FAIL: playwright exited 0 but no pass marker found"
        tail -50 "$TEST_OUT" | sed 's/^/[vz9t8_7_e2e]   /'
        FAIL=$((FAIL + 1))
    fi
else
    rc=$?
    echo "[vz9t8_7_e2e] FAIL: playwright exited $rc"
    tail -80 "$TEST_OUT" | sed 's/^/[vz9t8_7_e2e]   /'
    FAIL=$((FAIL + 1))
fi

# Summary report.
{
    echo "# Integrity TOFU Test Summary"
    echo ""
    echo "Generated by scripts/tests/vz9t8_7_integrity_tofu_e2e.sh"
    echo ""
    echo "## Tests run"
    echo ""
    grep -E "^[ ]*✓|^[ ]*✗|test result" "$TEST_OUT" 2>/dev/null | sed 's/^/    /' || true
    echo ""
    echo "## Pass/Fail"
    echo "PASS=$PASS FAIL=$FAIL"
} > "$SUMMARY"

echo ""
echo "[vz9t8_7_e2e] SUMMARY: PASS=$PASS FAIL=$FAIL"
echo "[vz9t8_7_e2e] log: $LOG"
echo "[vz9t8_7_e2e] summary: $SUMMARY"
[ "$FAIL" -eq 0 ] && echo "[vz9t8_7_e2e] ALL PASS" || exit 1
